# Site settings
title: An Gèidheal Ùr
description: Geàrr-chunntas sgrìobhte de naidheachdan LGDTCEN+ ionadail, nàiseanta ‘s bho air feadh an t-saoghail.
baseurl: "/angeidhealur" # the subpath of your site, e.g. /blog
url: "https://angeidheal.github.io" # the base hostname & protocol for your site

#footer
author: Crìstean MacMhìcheil
website: "https://criomagan.scot"

#social
mastodon: 
instagram: 
threads: 
email: fios@angeidhealur.scot

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 8
paginate_path: /duilleag-:num/

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
